version: '3.3'
services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - db_vol:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: ipadla/foodgram:v2
    restart: always
    depends_on:
      - db
    volumes:
      - static_vol:/app/static/
      - media_vol:/app/media/
    env_file:
      - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_vol:/var/html/static/
      - media_vol:/var/html/media/

volumes:
  db_vol:
  static_vol:
  media_vol:
