# Generated by Django 2.2.28 on 2022-08-02 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(regex='^#?[A-Fa-f0-9]{6}$')])),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'tags',
            },
        ),
    ]
