# Generated by Django 2.2.28 on 2022-08-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
