# Generated by Django 2.2.28 on 2022-08-05 17:37

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.BrinIndex(fields=['pub_date'], name='recipes_rec_pub_dat_7a8499_brin'),
        ),
    ]
