# Generated by Django 2.2.28 on 2022-07-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220726_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipefavorites',
            options={'verbose_name_plural': 'recipe favorites'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='tags.Tags'),
        ),
    ]
